# Generated by Django 2.2.15 on 2020-08-30 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
